# Generated by Django 4.2.5 on 2023-09-11 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_api', '0002_rename_transactions_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='currency_type',
        ),
    ]
