# Generated by Django 4.2.5 on 2023-09-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_api', '0003_remove_transaction_currency_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency_type',
            field=models.CharField(choices=[('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'British Pound (GBP)')], default='Unknown', max_length=1000),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user_id',
            field=models.CharField(max_length=200),
        ),
    ]
