# Generated by Django 4.2.4 on 2023-09-12 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_api', '0004_transaction_currency_type_alter_transaction_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='user_id',
            field=models.CharField(max_length=200, unique=False),
        ),
        migrations.CreateModel(
            name='registered_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('e_mail', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=12)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_id', to='financial_api.transaction')),
            ],
        ),
    ]
