# Generated by Django 4.2.4 on 2023-09-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_api', '0005_alter_transaction_user_id_registered_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registered_users',
        ),
    ]
