# Generated by Django 4.2.4 on 2023-09-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_api', '0009_alter_transaction_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='user_id',
            field=models.CharField(max_length=200),
        ),
    ]
