# Generated by Django 4.2.4 on 2023-09-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_api', '0010_alter_transaction_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=150)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
