# Generated by Django 4.2.4 on 2023-09-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_api', '0012_transaction_user_profile_userprofile_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='user_id',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
    ]
