# Generated by Django 4.2.4 on 2023-09-13 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_api', '0013_alter_transaction_user_id_alter_userprofile_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='user_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_id_transaction', to='financial_api.userprofile'),
        ),
    ]
