# Generated by Django 4.2.4 on 2023-09-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_api', '0014_alter_transaction_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
